// KOHAT ZALMI — Supabase-connected team dashboard
const SUPABASE_URL = "https://szojybwguxkydkdombqo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_yKCdQBSPvkisSWncHbGmBg_-6u9DEyP";
const OWNER_UID = "f62ca7bc-486d-462f-92dd-6415e0e90973";
const supabaseClient = window.supabase.createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
const THEME_KEY="kzTheme";
let state={players:[],matches:[]}, currentUser=null, isAdmin=false, pendingPhoto="";
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const n=v=>Number(v||0), avg=p=>n(p.dismissals)?n(p.runs)/n(p.dismissals):0, sr=p=>n(p.balls)?n(p.runs)/n(p.balls)*100:0, eco=p=>n(p.overs)?n(p.conceded)/n(p.overs):0;
const fmt=x=>n(x).toFixed(2), esc=v=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
function toast(msg){const t=$("#toast");if(!t)return;t.textContent=msg;t.classList.add("show");clearTimeout(window.kzToast);window.kzToast=setTimeout(()=>t.classList.remove("show"),2800)}
function avatar(p,cls=""){return p.photo?`<div class="avatar ${cls}"><img src="${p.photo}" alt="${esc(p.name)}"></div>`:`<div class="avatar ${cls}">${esc((p.name||"?")[0].toUpperCase())}</div>`}
function resultStats(){const m=state.matches;return{wins:m.filter(x=>x.result==="Won").length,losses:m.filter(x=>x.result==="Lost").length,ties:m.filter(x=>x.result==="Tied").length,nr:m.filter(x=>x.result==="No Result").length}}
function go(page){if(["add","addPlayer"].includes(page)&&!isAdmin){toast("Admin login is required.");openAuth();return}$$(".page").forEach(x=>x.classList.toggle("active",x.id===page));$$(".nav").forEach(x=>x.classList.toggle("active",x.dataset.page===page));const titles={dashboard:"Team Dashboard",players:"Players",matches:"Matches",rankings:"Rankings",analytics:"Analytics",venues:"Venues",leaders:"The Leaders Of Kohat Zalmi",add:"Add Data",addPlayer:"Add Player"};$("#pageTitle").textContent=titles[page]||"Kohat Zalmi";$("#pageSub").textContent=page==="dashboard"?"Kohat Zalmi performance center":isAdmin?"Kohat Zalmi • admin connected":"Kohat Zalmi • public view";render();window.scrollTo({top:0,behavior:"smooth"})}
$$('.nav').forEach(b=>b.onclick=()=>go(b.dataset.page));$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));
function bar(label,pct,value,cls=""){return `<div class="bar-row"><div class="bar-top"><span>${esc(label)}</span><b>${value!==""?esc(value):fmt(pct)+"%"}</b></div><div class="bar-track"><div class="bar-fill ${cls}" style="width:${Math.max(0,Math.min(100,pct))}%"></div></div></div>`}
function render(){const ps=state.players||[],ms=state.matches||[],runs=ps.reduce((a,p)=>a+n(p.runs),0),wk=ps.reduce((a,p)=>a+n(p.wickets),0),r=resultStats(),pct=ms.length?r.wins/ms.length*100:0;$("#summaryCards").innerHTML=[["Players",ps.length,"Team squad"],["Matches",ms.length,"Recorded matches"],["Total Runs",runs,"All players"],["Total Wickets",wk,"All bowlers"]].map(x=>`<div class="stat reveal"><div class="label">${x[0]}</div><div class="value">${x[1]}</div><div class="sub">${x[2]}</div></div>`).join("");$("#wins").textContent=r.wins;$("#losses").textContent=r.losses;$("#ties").textContent=r.ties;$("#nr").textContent=r.nr;$("#winPct").textContent=fmt(pct)+"%";$("#winCircle").style.background=`conic-gradient(#0b8275 0 ${pct}%,#dbe5e4 ${pct}% 100%)`;const top=[...ps].sort((a,b)=>n(b.runs)-n(a.runs)).slice(0,5);$("#topPerformers").innerHTML=top.length?top.map(p=>`<div class="performer">${avatar(p)}<div class="grow"><b>${esc(p.name)}</b><div class="muted">${esc(p.role)} • #${esc(p.jersey)} • ${n(p.matches)} matches</div></div><b>${n(p.runs)} runs</b></div>`).join(""):empty("No players yet.");$("#recentMatches").innerHTML=ms.length?ms.slice().sort((a,b)=>String(b.date).localeCompare(String(a.date))).slice(0,5).map(m=>`<div class="performer"><div class="grow"><b>${esc(m.opponent)}</b><div class="muted">${esc(m.date)} • ${esc(m.venue)}</div></div><span class="${m.result==="Won"?"win":m.result==="Lost"?"loss":""}">${esc(m.result)}</span></div>`).join(""):empty("No matches recorded yet.");$("#snapshotBars").innerHTML=bar("Win rate",pct,"")+bar("Matches played",Math.min(ms.length*10,100),ms.length)+bar("Squad active",ps.length?100:0,ps.length+" players");renderPlayers();renderMatches();renderRankings();renderAnalytics();renderVenues();fillPlayerSelect();applyAccessUI()}
function empty(s){return `<div class="empty">${s}</div>`}
function renderPlayers(){const q=($("#playerSearch")?.value||"").toLowerCase(),role=$("#roleFilter")?.value||"all",ps=state.players.filter(p=>String(p.name||"").toLowerCase().includes(q)&&(role==="all"||p.role===role));$("#playersGrid").innerHTML=ps.length?ps.map(p=>`<div class="player-card" onclick="showPlayer('${String(p.id)}')"><div class="player-top">${avatar(p)}<div class="grow"><h3>${esc(p.name)}</h3><div class="role">${esc(p.role)} • Jersey #${esc(p.jersey)}</div></div></div><div class="mini-stats"><div><b>${n(p.runs)}</b><span>Runs</span></div><div><b>${fmt(sr(p))}</b><span>SR</span></div><div><b>${n(p.wickets)}</b><span>Wkts</span></div></div>${isAdmin?`<div class="card-actions"><button class="action-btn" onclick="event.stopPropagation();editPlayer('${String(p.id)}')">Edit</button><button class="action-btn delete-player" onclick="event.stopPropagation();deletePlayer('${String(p.id)}')">Delete</button></div>`:""}</div>`).join(""):empty("No players found.")}
function renderMatches(){const season=$("#matchSeason")?.value||"all",ms=state.matches.filter(m=>season==="all"||String(m.date||"").startsWith(season)).slice().sort((a,b)=>String(b.date).localeCompare(String(a.date)));$("#matchesTable").innerHTML=ms.length?ms.map(m=>{const bestB=[...state.players].sort((a,b)=>n(b.runs)-n(a.runs))[0],bestW=[...state.players].sort((a,b)=>n(b.wickets)-n(a.wickets))[0];return `<tr><td>${esc(m.date)}</td><td>${esc(m.opponent)}</td><td>${esc(m.venue)}</td><td class="${m.result==="Won"?"win":m.result==="Lost"?"loss":""}">${esc(m.result)}</td><td>${esc(m.score)}</td><td>${bestB?esc(bestB.name)+" ("+n(bestB.runs)+")":"—"}</td><td>${bestW?esc(bestW.name)+" ("+n(bestW.wickets)+")":"—"}</td><td class="admin-col">${isAdmin?`<button class="action-btn" onclick="editMatch('${String(m.id)}')">Edit</button> <button class="action-btn delete-player" onclick="deleteMatch('${String(m.id)}')">Delete</button>`:"—"}</td></tr>`}).join(""):`<tr><td colspan="8" class="empty">No matches recorded yet.</td></tr>`}
function rankingRows(arr,value,label){return arr.slice(0,3).map((p,i)=>`<div class="rank-row"><div class="rank-no">${i+1}</div>${avatar(p)}<div class="grow"><b>${esc(p.name)}</b><div class="muted">${esc(p.role)} • #${esc(p.jersey)}</div></div><div class="rank-value">${value(p)}<div class="muted">${label}</div></div></div>`).join("")||empty("No players yet.")}
function renderRankings(){const bat=[...state.players].sort((a,b)=>n(b.runs)-n(a.runs)),bowl=[...state.players].sort((a,b)=>n(b.wickets)-n(a.wickets)),ar=[...state.players].filter(p=>String(p.role||"").toLowerCase().replace(/[\s-]/g,"")==="allrounder").sort((a,b)=>(n(b.runs)+n(b.wickets)*20)-(n(a.runs)+n(a.wickets)*20)),all=[...state.players].sort((a,b)=>(n(b.runs)+n(b.wickets)*20)-(n(a.runs)+n(a.wickets)*20));$("#batRank").innerHTML=rankingRows(bat,p=>n(p.runs),"runs");$("#bowlRank").innerHTML=rankingRows(bowl,p=>n(p.wickets),"wickets");$("#arRank").innerHTML=rankingRows(ar,p=>`${n(p.runs)}/${n(p.wickets)}`,"runs/wkts");$("#rankingTable").innerHTML=all.length?all.map((p,i)=>`<tr><td>${i+1}</td><td><div class="rank-player-cell">${avatar(p)}<b>${esc(p.name)}</b></div></td><td>${esc(p.role)}</td><td>${n(p.runs)}</td><td>${fmt(avg(p))}</td><td>${fmt(sr(p))}</td><td>${n(p.wickets)}</td><td>${n(p.overs)?fmt(eco(p)):"—"}</td><td>${n(p.matches)}</td></tr>`).join(""):`<tr><td colspan="9" class="empty">No players yet.</td></tr>`}
function renderAnalytics(){const r=resultStats(),ms=state.matches,runs=state.players.reduce((a,p)=>a+n(p.runs),0),wk=state.players.reduce((a,p)=>a+n(p.wickets),0),bestSR=[...state.players].sort((a,b)=>sr(b)-sr(a))[0],bestEco=[...state.players].filter(p=>n(p.overs)>0).sort((a,b)=>eco(a)-eco(b))[0];$("#analyticsCards").innerHTML=[["Win Rate",ms.length?fmt(r.wins/ms.length*100)+"%":"0%","Overall"],["Wins",r.wins,"Matches won"],["Losses",r.losses,"Matches lost"],["Best SR",bestSR?fmt(sr(bestSR)):"—",bestSR?bestSR.name:""]].map(x=>`<div class="stat"><div class="label">${x[0]}</div><div class="value">${x[1]}</div><div class="sub">${esc(x[2])}</div></div>`).join("");const total=Math.max(ms.length,1);$("#resultBars").innerHTML=bar("Won",r.wins/total*100,r.wins)+bar("Lost",r.losses/total*100,r.losses,"red")+bar("Tied",r.ties/total*100,r.ties,"gold")+bar("No Result",r.nr/total*100,r.nr);$("#performanceBars").innerHTML=bar("Total runs",Math.min(runs/5,100),runs)+bar("Total wickets",Math.min(wk*5,100),wk)+bar("Best bowling economy",bestEco?Math.max(0,100-eco(bestEco)*10):0,bestEco?fmt(eco(bestEco)):"—");const ps=[...state.players].sort((a,b)=>(n(b.runs)+n(b.wickets)*15)-(n(a.runs)+n(a.wickets)*15)).slice(0,8);$("#playerEfficiency").innerHTML=ps.length?ps.map(p=>bar(p.name,Math.min(100,n(p.runs)/3+n(p.wickets)*3),`${n(p.runs)} runs • ${n(p.wickets)} wkts`)).join(""):empty("No player data yet.")}
function renderVenues(){const map={};state.matches.forEach(m=>{const v=m.venue||"Unknown";map[v]??={matches:0,wins:0};map[v].matches++;if(m.result==="Won")map[v].wins++});const a=Object.entries(map);$("#venueCards").innerHTML=a.length?a.map(([v,x])=>`<div class="stat"><div class="label">VENUE</div><div class="value">${esc(v)}</div><div class="sub">${x.matches} matches • ${fmt(x.wins/x.matches*100)}% wins</div></div>`).join(""):empty("No venue data yet.");$("#venueTable").innerHTML=a.length?a.map(([v,x])=>`<tr><td>${esc(v)}</td><td>${x.matches}</td><td>${x.wins}</td><td>${fmt(x.wins/x.matches*100)}%</td></tr>`).join(""):`<tr><td colspan="4" class="empty">No venue data yet.</td></tr>`}
function fillPlayerSelect(){$("#perfPlayer").innerHTML=state.players.map(p=>`<option value="${esc(p.id)}">${esc(p.name)} — ${esc(p.role)} (#${esc(p.jersey)})</option>`).join("")||'<option value="">No players — add a player first</option>'}
function showPlayer(id){const p=state.players.find(x=>String(x.id)===String(id));if(!p)return;$("#playerDetail").innerHTML=`<div class="detail-head">${avatar(p)}<div><h2>${esc(p.name)}</h2><div class="role">${esc(p.role)} • Jersey #${esc(p.jersey)}</div></div></div><div class="detail-grid">${[["Matches",n(p.matches)],["Runs",n(p.runs)],["Average",fmt(avg(p))],["Strike Rate",fmt(sr(p))],["Wickets",n(p.wickets)],["Economy",n(p.overs)?fmt(eco(p)):"—"],["Balls",n(p.balls)],["Overs",n(p.overs)]].map(x=>`<div class="detail-stat"><b>${x[1]}</b><span>${x[0]}</span></div>`).join("")}</div>${isAdmin?`<div class="detail-actions"><button class="primary" onclick="editPlayer('${String(p.id)}')">Edit Player</button><button class="action-btn delete-player" onclick="deletePlayer('${String(p.id)}');closeModal()">Delete Player</button></div>`:""}`;$("#playerModal").classList.add("show")}
function closeModal(){$("#playerModal")?.classList.remove("show")}$("#closeModal").onclick=closeModal;$("#playerModal").onclick=e=>{if(e.target.id==="playerModal")closeModal()};
async function deletePlayer(id){if(!isAdmin)return toast("Admin login required.");const p=state.players.find(x=>String(x.id)===String(id));if(!p||!confirm(`Delete ${p.name}? This cannot be undone.`))return;const {error}=await supabaseClient.from("kohat zalmi").delete().eq("id",id);if(error)return toast("Delete failed: "+error.message);state.players=state.players.filter(x=>String(x.id)!==String(id));closeModal();render();toast("Player deleted.")}
async function editPlayer(id){if(!isAdmin)return toast("Admin login required.");const p=state.players.find(x=>String(x.id)===String(id));if(!p)return;const name=prompt("Player name:",p.name||"");if(name===null)return;const jersey=prompt("Jersey number:",p.jersey||"");if(jersey===null)return;const role=prompt("Role (Batter, Bowler, All-rounder, Wicketkeeper):",p.role||"");if(role===null)return;if(!name.trim())return toast("Player name is required.");const {data,error}=await supabaseClient.from("kohat zalmi").update({name:name.trim(),jersey:jersey.trim(),role:role.trim()}).eq("id",id).select().single();if(error)return toast("Update failed: "+error.message);const i=state.players.findIndex(x=>String(x.id)===String(id));if(i>=0)state.players[i]=data;closeModal();render();toast("Player updated.")}
async function deleteMatch(id){if(!isAdmin)return toast("Admin login required.");if(!confirm("Delete this match? This cannot be undone."))return;const {error}=await supabaseClient.from("matches").delete().eq("id",id);if(error)return toast("Delete failed: "+error.message);state.matches=state.matches.filter(x=>String(x.id)!==String(id));render();toast("Match deleted.")}
async function editMatch(id){if(!isAdmin)return toast("Admin login required.");const m=state.matches.find(x=>String(x.id)===String(id));if(!m)return;const date=prompt("Date (YYYY-MM-DD):",m.date||"");if(date===null)return;const opponent=prompt("Opponent:",m.opponent||"");if(opponent===null)return;const venue=prompt("Venue:",m.venue||"");if(venue===null)return;const result=prompt("Result (Won, Lost, Tied, No Result):",m.result||"");if(result===null)return;const score=prompt("Kohat Zalmi score:",m.score||"");if(score===null)return;const {data,error}=await supabaseClient.from("matches").update({date,opponent,venue,result,score}).eq("id",id).select().single();if(error)return toast("Update failed: "+error.message);const i=state.matches.findIndex(x=>String(x.id)===String(id));if(i>=0)state.matches[i]=data;render();toast("Match updated.")}
$("#playerSearch").oninput=renderPlayers;$("#roleFilter").onchange=renderPlayers;$("#matchSeason").onchange=renderMatches;
$("#matchForm").onsubmit=async e=>{e.preventDefault();if(!isAdmin)return toast("Admin login required.");const f=new FormData(e.target),match={date:f.get("date"),opponent:f.get("opponent"),venue:f.get("venue"),result:f.get("result"),score:f.get("score")};const {data,error}=await supabaseClient.from("matches").insert([match]).select().single();if(error)return toast("Could not save match: "+error.message);state.matches.push(data);e.target.reset();toast("Match saved successfully.");go("matches")};
$("#perfForm").onsubmit=async e=>{e.preventDefault();if(!isAdmin)return toast("Admin login required.");const f=new FormData(e.target),p=state.players.find(x=>String(x.id)===String(f.get("player")));if(!p){toast("Add a player first.");go("addPlayer");return}const updates={matches:n(p.matches)+1,runs:n(p.runs)+n(f.get("runs")),balls:n(p.balls)+n(f.get("balls")),dismissals:n(p.dismissals)+n(f.get("dismissed")),overs:n(p.overs)+n(f.get("overs")),conceded:n(p.conceded)+n(f.get("conceded")),wickets:n(p.wickets)+n(f.get("wickets"))};const {data,error}=await supabaseClient.from("kohat zalmi").update(updates).eq("id",p.id).select().single();if(error)return toast("Could not save performance: "+error.message);Object.assign(p,data);e.target.reset();toast("Performance saved.");go("players")};
function fileToDataURL(file){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file)})}
$("#playerForm").onsubmit=async e=>{e.preventDefault();if(!isAdmin)return toast("Admin login required.");const f=new FormData(e.target);let photo=pendingPhoto;const file=f.get("photo");if(file&&file.size)photo=await fileToDataURL(file);const name=String(f.get("name")||"").trim();if(!name)return toast("Enter a player name.");const player={name,jersey:String(f.get("jersey")||"").trim(),role:String(f.get("role")||"").trim(),photo:photo||"",matches:0,runs:0,balls:0,dismissals:0,overs:0,conceded:0,wickets:0};const {data,error}=await supabaseClient.from("kohat zalmi").insert([player]).select().single();if(error)return toast("Could not add player: "+error.message);state.players.push(data);e.target.reset();pendingPhoto="";$("#photoPreview").src="";$("#photoPreview").classList.remove("show");$("#photoHint").textContent="Optional • upload a player photo";toast("Player added.");go("players")};
$("#playerForm [name=photo]").onchange=async e=>{const f=e.target.files[0];if(!f)return;if(f.size>2*1024*1024){toast("Please choose a photo under 2 MB.");e.target.value="";return}pendingPhoto=await fileToDataURL(f);$("#photoPreview").src=pendingPhoto;$("#photoPreview").classList.add("show");$("#photoHint").textContent=f.name};
$("#clearBtn").onclick=async()=>{if(!isAdmin)return toast("Admin login required.");if(!confirm("Clear ALL players and matches? This cannot be undone."))return;for(const table of ["matches","kohat zalmi"]){const q=await supabaseClient.from(table).select("id");if(q.error)return toast("Could not clear "+table+": "+q.error.message);for(const row of q.data||[]){const d=await supabaseClient.from(table).delete().eq("id",row.id);if(d.error)return toast("Could not clear "+table+": "+d.error.message)}}state={players:[],matches:[]};render();go("dashboard");toast("All team data cleared.")};
$("#exportBtn").onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="kohat-zalmi-data.json";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
function setTheme(t){document.body.classList.toggle("night",t==="night");$("#themeBtn").textContent=t==="night"?"☀️ Day":"🌙 Night";localStorage.setItem(THEME_KEY,t)}const savedTheme=localStorage.getItem(THEME_KEY);setTheme(savedTheme||((new Date()).getHours()>=18||(new Date()).getHours()<6?"night":"day"));$("#themeBtn").onclick=()=>setTheme(document.body.classList.contains("night")?"day":"night");
function applyAccessUI(){$$(".admin-only").forEach(x=>x.classList.toggle("hidden",!isAdmin));$$(".admin-page").forEach(x=>x.classList.toggle("hidden",!isAdmin));$$(".admin-col").forEach(x=>x.classList.toggle("hidden",!isAdmin));$("#accessLabel").textContent=isAdmin?"ADMIN MODE":"VISITOR MODE";$("#authStatus").classList.toggle("admin",isAdmin);$("#authStatus").innerHTML=`<i></i> ${isAdmin?"Admin":"Visitor"}`;$("#loginBtn").classList.toggle("hidden",isAdmin);$("#logoutBtn").classList.toggle("hidden",!isAdmin)}
function openAuth(){$("#authModal").classList.add("show");$("#loginMessage").textContent=""}function closeAuth(){$("#authModal").classList.remove("show")}$("#loginBtn").onclick=openAuth;$("#closeAuth").onclick=closeAuth;$("#authModal").onclick=e=>{if(e.target.id==="authModal")closeAuth()};
$("#loginForm").onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);$("#loginMessage").textContent="Signing in...";const {data,error}=await supabaseClient.auth.signInWithPassword({email:f.get("email"),password:f.get("password")});if(error){$("#loginMessage").textContent=error.message;return}currentUser=data.user;isAdmin=String(currentUser?.id||"")===OWNER_UID;closeAuth();e.target.reset();if(isAdmin){toast("Welcome, admin. Write controls are enabled.");go("dashboard")}else{toast("This account is view-only.");render()}};
$("#logoutBtn").onclick=async()=>{await supabaseClient.auth.signOut();currentUser=null;isAdmin=false;applyAccessUI();toast("Signed out.");go("dashboard")};
async function loadData(){const [p,m]=await Promise.all([supabaseClient.from("kohat zalmi").select("*").order("id",{ascending:true}),supabaseClient.from("matches").select("*").order("date",{ascending:false})]);if(p.error)toast("Players could not be loaded: "+p.error.message);else state.players=p.data||[];if(m.error)toast("Matches could not be loaded: "+m.error.message);else state.matches=m.data||[];render()}
async function initAuth(){const {data}=await supabaseClient.auth.getSession();currentUser=data.session?.user||null;isAdmin=String(currentUser?.id||"")===OWNER_UID;applyAccessUI();supabaseClient.auth.onAuthStateChange((_e,s)=>{currentUser=s?.user||null;isAdmin=String(currentUser?.id||"")===OWNER_UID;applyAccessUI();render()})}
(async()=>{await initAuth();await loadData()})();
